import type { Metadata } from "next";
import { ContactCta } from "@/components/sections/contact-cta";
import { Atlas, Eyebrow, PageHero } from "@/components/ui/primitives";

export const metadata: Metadata = { title: "About", description: "Apex Capital Partners offers private, considered advisory support from Saint Kitts and Nevis." };

export default function AboutPage() {
  return <><PageHero eyebrow="About Apex" title="Clarity before commitment." intro="A boutique advisory perspective for people making consequential decisions across citizenship, investment, and travel." index="01" /><section className="light-section narrative"><div className="shell narrative-grid"><Eyebrow>Our position</Eyebrow><div><h2>Based in Saint Kitts and Nevis. Oriented internationally.</h2><p className="lead">Apex Capital Partners helps clients approach complex opportunities with discretion, context, and a disciplined sequence of questions.</p><p>We do not begin with promises. We begin by understanding the client, the family, the intended outcome, and the practical constraints that matter. From there, we help organize relevant information and define the next appropriate step.</p></div><aside><Atlas compact /></aside></div></section><section className="values-section"><div className="shell values-grid"><div><Eyebrow>How we work</Eyebrow><h2>Private office principles.</h2></div>{[["01","Discretion","Personal circumstances deserve careful handling and measured conversation."],["02","Clarity","We distinguish general information from what requires current, professional verification."],["03","Consideration","A suitable path must account for priorities, dependants, timing, and risk."],["04","Coordination","We help clients keep practical questions and moving parts in view."]].map(([n,t,d]) => <article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section><section className="scope-band dark-section"><div className="shell"><Eyebrow dark>Scope</Eyebrow><h2>Guidance without overstatement.</h2><p>Our support covers citizenship by investment orientation, property opportunity evaluation, travel assistance, tourist visa preparation, and accommodation planning. Where legal, financial, government, or third-party decisions apply, those decisions remain independent and require direct verification.</p></div></section><ContactCta /></>;
}
