"use client";
/* eslint-disable @next/next/no-img-element */

import { ChangeEvent, useState } from "react";
import { validateMediaFile } from "@/lib/media-validation";

type Media = { id: string; file_name: string; original_file_name: string; media_type: "image" | "video"; public_url: string; file_size: number; mime_type: string; created_at: string };
const size = (bytes: number) => `${(bytes / 1024 / 1024).toFixed(1)} MB`;

export function MediaManager({ initialMedia }: { initialMedia: Media[] }) {
  const [media, setMedia] = useState<Media[]>(initialMedia); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [uploadNames, setUploadNames] = useState<Record<Media["media_type"], string>>({ image: "", video: "" });
  async function refresh() { const response = await fetch("/api/admin/media"); const data = await response.json(); if (!response.ok) { setError(data.error || "Could not load media."); return; } setMedia(data.media); }
  async function upload(event: ChangeEvent<HTMLInputElement>, type: Media["media_type"]) { const file = event.target.files?.[0]; event.target.value = ""; if (!file) return; const validation = validateMediaFile(file); if (!validation.ok || validation.mediaType !== type) { setError(validation.ok ? "Choose the correct media type." : validation.message); return; } setBusy(true); setError(""); try { const signatureResponse = await fetch("/api/admin/media/signature", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ mediaType: type, name: uploadNames[type] || file.name }) }); const signature = await signatureResponse.json(); if (!signatureResponse.ok) throw new Error(signature.error || "Could not prepare upload."); const cloudinaryBody = new FormData(); cloudinaryBody.append("file", file); cloudinaryBody.append("api_key", signature.apiKey); cloudinaryBody.append("timestamp", String(signature.timestamp)); cloudinaryBody.append("signature", signature.signature); cloudinaryBody.append("public_id", signature.publicId); const cloudinaryResponse = await fetch(`https://api.cloudinary.com/v1_1/${signature.cloudName}/${type}/upload`, { method: "POST", body: cloudinaryBody }); const cloudinary = await cloudinaryResponse.json(); if (!cloudinaryResponse.ok) throw new Error(cloudinary.error?.message || "Cloudinary upload failed."); const response = await fetch("/api/admin/media", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ publicId: cloudinary.public_id, resourceType: cloudinary.resource_type, originalName: file.name, name: uploadNames[type], mediaType: type }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Could not save media details."); setUploadNames((current) => ({ ...current, [type]: "" })); await refresh(); } catch (uploadError) { setError(uploadError instanceof Error ? uploadError.message : "Upload failed."); } finally { setBusy(false); } }
  async function remove(item: Media) { if (!window.confirm("Delete this media permanently?")) return; setBusy(true); setError(""); const response = await fetch(`/api/admin/media/${item.id}`, { method: "DELETE" }); const data = await response.json(); if (!response.ok) setError(data.error || "Delete failed."); else await refresh(); setBusy(false); }
  const renderGroup = (type: Media["media_type"], label: string, limit: number) => { const items = media.filter((item) => item.media_type === type); return <section className="admin-media-group"><div className="admin-section-heading"><div><p className="eyebrow text-brass">{label}</p><h2>{items.length} / {limit}</h2></div><div className="admin-upload-control"><input className="admin-media-name-input" type="text" value={uploadNames[type]} onChange={(event) => setUploadNames((current) => ({ ...current, [type]: event.target.value }))} placeholder="Optional public filename" maxLength={80} aria-label={`Optional ${label.toLowerCase()} filename`} /><label className="admin-button admin-button-primary">+ Upload {label.slice(0, -1)}<input type="file" accept={type === "image" ? "image/jpeg,image/png,image/webp" : "video/mp4,video/webm"} onChange={(event) => upload(event, type)} hidden /></label></div></div>{items.length === 0 ? <p className="admin-empty">No {label.toLowerCase()} are published yet.</p> : <div className="admin-media-grid">{items.map((item) => <article className="admin-media-card" key={item.id}>{item.media_type === "image" ? <img src={item.public_url} alt={item.original_file_name} /> : <video src={item.public_url} controls preload="metadata" />}<div><strong>{item.file_name}</strong><span>{item.original_file_name !== item.file_name ? `Source: ${item.original_file_name} · ` : ""}{size(item.file_size)} · {new Date(item.created_at).toLocaleDateString()}</span><button className="admin-button admin-button-danger" onClick={() => remove(item)} disabled={busy}>Delete</button></div></article>)}</div>}</section>; };
  return <main className="admin-page"><div className="admin-page-heading"><div><p className="eyebrow text-brass">Media</p><h1>Keep the website current.</h1><p>Upload up to five images and three videos. New uploads appear on the public media page.</p></div></div>{error && <p className="admin-error" role="alert">{error}</p>}{busy && <p className="admin-notice" role="status">Updating media...</p>}{renderGroup("image", "Images", 5)}{renderGroup("video", "Videos", 3)}</main>;
}
